# site setup
exclude:
  - README.md
  - BUILD.md
  - .gitignore
  - LICENSE
permalink: /:title/
markdown: kramdown
baseurl: /~enm5310
url: https://www.seas.upenn.edu
githuburl: https://github.com/PredictiveIntelligenceLab/ENM5310
edurl: https://edstem.org/us/courses/34160/discussion/
canvasurl: https://canvas.upenn.edu/courses/1704774
zoomlecturesurl: https://upenn.zoom.us/j/94544521380
zoomofficehoursurl: https://upenn.zoom.us/j/99270285897
# course setup
title: "Data-driven Modeling and Probabilistic Scientific Computing"
semester: "Spring 2023"
duration: "14 Weeks"
instructor:
 - Paris Perdikaris
email:
 - pgp@seas.upenn.edu
coursecode:
 - "ENM 5310"
coursedates:
 - "January 12 to April 26, 2023"
coursetime: "Tuesdays and Thursdays, 3:30pm to 5:00pm (Towne 309)"
officehourstime: "Thursdays, 12:00pm to 2:00pm (Rm. 527A, 3401 Walnut Street, 5th floor)"
courselocation:
 - "Towne 309"
communication:
 -
   name: "Email"
   description: "For questions, comments and class updates"
   details:
officehours:
- description: "Thursdays, 12:00pm to 2:00pm"
# Tachyons Version
tv: "4.6.1"

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# SCSS Compress
sass:
  style: compressed


# Bibtex
  gems: ['jekyll/scholar']
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Includes an icon in the footer for each username you enter
footer-links:
  github: barryclark/jekyll-now
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
